"""create_tables

Revision ID: 94b0e0e9fad5
Revises: 
Create Date: 2023-05-12 11:19:18.062663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b0e0e9fad5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_symptom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=30), nullable=False),
    sa.Column('symptom_code', sa.String(length=30), nullable=False),
    sa.Column('symptom_name', sa.String(length=30), nullable=False),
    sa.Column('symptom_diagnostic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_symptom_data')
    # ### end Alembic commands ###
